# Generated by Django 3.2 on 2023-09-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20220219_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(default='1402-07-01', max_length=50, verbose_name='تاریخ کلاس'),
        ),
    ]
